import {
  BellRinging,
  Browsers,
  Calendar,
  Cards,
  CaretDoubleRight,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChartPie,
  DotsThreeCircle,
  IconProps,
  ListNumbers,
  Minus,
  Notification,
  Option,
  PictureInPicture,
  RadioButton,
  Sidebar,
  SlidersHorizontal,
  User,
  Warning,
} from 'phosphor-react'
import { ForwardRefExoticComponent, RefAttributes } from 'react'
import { v4 as generatedID } from 'uuid'

export interface routerPath {
  id: string
  name: string
  href: string
  tag?: boolean
  deprecate?: boolean
  redirect?: boolean
  folderName?: string
  target?: string
  Icon?: ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>
}

export const routes: routerPath[] = [
  {
    id: generatedID(),
    name: 'UPSC',
    href: '',
    tag: false,
    deprecate: false,
    folderName: 'UPSC',
    Icon: Browsers,
  },
  {
    id: generatedID(),
    name: 'MPPSC',
    href: '',
    tag: false,
    deprecate: false,
    folderName: 'MPPSC',
    Icon: Warning,
  },
  {
    id: generatedID(),
    name: 'UPPSC',
    href: '',
    tag: false,
    deprecate: false,
    folderName: 'UPPSC',
    Icon: ChartLineUp,
  },
  {
    id: generatedID(),
    name: 'CTET',
    folderName: 'CTET',
    href: '',
    tag: false,
    deprecate: false,
    Icon: ChartBar,
  },
  {
    id: generatedID(),
    name: 'IPBS PO',
    folderName: 'IPBS PO',
    href: '',
    tag: false,
    deprecate: false,
    Icon: ChartLine,
  },
  {
    id: generatedID(),
    name: 'SBI PO',
    folderName: 'SBI PO',
    href: '',
    tag: false,
    deprecate: false,
    Icon: ChartPie,
  },
  {
    id: generatedID(),
    name: 'NABARD',
    href: '',
    tag: false,
    deprecate: false,
    folderName: 'NABARD',
    Icon: User,
  },
  {
    id: generatedID(),
    name: 'KVS',
    folderName: 'KVS',
    href: '',
    tag: false,
    deprecate: false,
    Icon: Notification,
  },

  {
    id: generatedID(),
    name: 'SSC CGL',
    folderName: 'SSC CGL',
    href: '',
    tag: false,
    deprecate: false,
    Icon: CaretDoubleRight,
  },
  {
    id: generatedID(),
    name: 'SSC CHSL',
    folderName: 'SSC CHSL',
    href: '',
    tag: false,
    deprecate: false,
    Icon: RadioButton,
  },
  {
    id: generatedID(),
    name: 'RRB NTPC',
    folderName: 'RRB NTPC',
    href: '',
    tag: false,
    deprecate: false,
    Icon: DotsThreeCircle,
  },
  {
    id: generatedID(),
    name: 'NDA',
    folderName: 'NDA',
    href: '',
    tag: false,
    deprecate: false,
    Icon: Cards,
  },
  {
    id: generatedID(),
    name: 'CDS',
    folderName: 'CDS',
    href: '',
    tag: false,
    deprecate: false,
    Icon: SlidersHorizontal,
  },
  {
    id: generatedID(),
    name: 'TETs',
    folderName: 'TETs',
    href: '',
    tag: false,
    deprecate: false,
    Icon: Minus,
  },
  {
    id: generatedID(),
    name: 'RBI Grade B',
    folderName: 'RBI Grade B',
    href: '',
    tag: false,
    deprecate: false,
    Icon: Calendar,
  },
  {
    id: generatedID(),
    name: 'MPSC',
    folderName: 'MPSC',
    href: '',
    tag: false,
    deprecate: false,
    Icon: Option,
  },
  {
    id: generatedID(),
    name: 'DSSSB',
    folderName: 'DSSSB',
    href: '',
    tag: false,
    deprecate: false,
    Icon: Sidebar,
  },
  {
    id: generatedID(),
    name: 'ISC',
    folderName: 'ISC',
    href: '',
    tag: false,
    deprecate: false,
    Icon: PictureInPicture,
  },
  // {
  //   id: generatedID(),
  //   name: 'Navbar',
  //   folderName: 'Navbar',
  //   href: '/docs/components/navbar',
  //   tag: false,
  //   deprecate: false,
  //   Icon: Browser,
  // },
  {
    id: generatedID(),
    name: 'SBI PO',
    folderName: 'SBI PO',
    href: '',
    tag: false,
    deprecate: false,
    Icon: BellRinging,
  },
  {
    id: generatedID(),
    name: 'UPPSC',
    folderName: 'UPPSC',
    href: '',
    tag: false,
    deprecate: false,
    Icon: ListNumbers,
  },
  {
    id: generatedID(),
    name: 'Progress',
    folderName: 'Progress',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Pagination',
    folderName: 'Pagination',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Popover',
    folderName: 'Popover',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Radio',
    folderName: 'FormControls',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Rating',
    folderName: 'Rating',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Sidebar',
    folderName: 'Sidebar',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Skeleton',
    folderName: 'Skeleton',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Slider',
    folderName: 'Slider',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Select',
    folderName: 'Select',
    href: '',
    tag: true,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Spinner',
    folderName: 'Spinner',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Steps',
    folderName: 'Steps',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Switch',
    folderName: 'FormControls',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Table',
    folderName: 'Table',
    href: '',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Tabs',
    folderName: 'Tabs',
    href: '/docs/components/tabs',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Text Area',
    folderName: 'FormControls',
    href: '/docs/components/textArea',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Toast',
    folderName: 'Toast',
    href: '/docs/components/toast',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Input',
    folderName: 'Input',
    href: '/docs/components/input',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Input OTP',
    folderName: 'Input OTP',
    href: '/docs/components/inputOtp',
    tag: true,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Timeline',
    folderName: 'Timeline',
    href: '/docs/components/timeline',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Tooltip',
    folderName: 'Tooltip',
    href: '/docs/components/tooltip',
    tag: false,
    deprecate: false,
  },
  {
    id: generatedID(),
    name: 'Upload',
    folderName: 'Upload',
    href: '/docs/components/upload',
    tag: false,
    deprecate: false,
  },
]

export const gettingStartedRoutes: routerPath[] = [
  {
    id: generatedID(),
    name: 'Installation',
    href: '/docs/getting-started/installation',
  },
  {
    id: generatedID(),
    name: 'Typography',
    href: '/docs/getting-started/typography',
  },
  {
    id: generatedID(),
    name: 'Colors',
    href: '/docs/getting-started/colors',
  },
  {
    id: generatedID(),
    name: 'Dark Mode',
    href: '/docs/getting-started/dark-mode',
  },
]

export const quickAccessRoute: routerPath[] = [
  {
    id: generatedID(),
    name: 'Installation',
    href: '/docs/getting-started/installation',
    target: '_self',
  },
  {
    id: generatedID(),
    name: 'Figma',
    href: 'https://byolacademy.com/',
    target: '_blank',
  },
  {
    id: generatedID(),
    name: 'Typography',
    href: '/docs/getting-started/typography',
    target: '_self',
  },
  {
    id: generatedID(),
    name: 'Colors',
    href: '/docs/getting-started/colors',
    target: '_self',
  },
  {
    id: generatedID(),
    name: 'Dark Mode',
    href: '/docs/getting-started/dark-mode',
    target: '_self',
  },
]

export const navbarRoutes: routerPath[] = [
  {
    id: generatedID(),
    href: '/',
    name: 'Home',
    redirect: true,
  },
  {
    id: generatedID(),
    href: '/',
    name: 'Releases',
    redirect: true,
  },
  {
    id: generatedID(),
    href: '/',
    name: 'Exams',
    redirect: true,
  },
  {
    id: generatedID(),
    href: '/blog',
    name: 'Blog',
    redirect: false,
  },
  {
    id: generatedID(),
    href: '/about',
    name: 'About',
    redirect: false,
  },
]
